[package]
name = "server"
version = "0.1.0"
edition = "2024"


[dependencies]
axum = "0.8.6"
tokio = { version = "1.48.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.18.1", features = ["v4"] }
cln-rpc = "0.4.0"
serde_json = "1"